/** Every route the app serves — shared by the verification scripts. */
export const ROUTES = [
  '/',
  '/dev-hub',
  '/cli-basics',
  '/decorator-pattern',
  '/video-lesson',
  '/architecture-deep-dive',
  '/git-branching',
  '/big-o-performance',
  '/data-structures-visual',
  '/api-anatomy',
  '/framework-comparison',
  '/quiz-mode',
  '/flashcards',
  '/algorithm-visualizer',
  '/code-playground',
  '/terminal-simulator',
  '/debugging-challenge',
  '/regex-lab',
  '/project-build-along',
  '/cheat-sheet',
  '/glossary',
  '/roadmap',
  '/progress-dashboard',
  '/course-complete',
]
